function FVector = fVec(Ixx,Iyy,Izz,LhS,LhdS,g,m,phiS,phidS,psiS,psidS,thtS,thtdS,xddS,yddS)
%FVEC
%    FVECTOR = FVEC(IXX,IYY,IZZ,LHS,LHDS,G,M,PHIS,PHIDS,PSIS,PSIDS,THTS,THTDS,XDDS,YDDS)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    22-Apr-2020 17:42:56

t2 = cos(phiS);
t3 = cos(psiS);
t4 = cos(thtS);
t5 = sin(phiS);
t6 = sin(psiS);
t7 = sin(thtS);
t8 = LhS.^2;
t9 = phidS.^2;
t10 = psiS.*2.0;
t11 = thtS.*2.0;
t12 = thtdS.^2;
t13 = t3.^2;
t14 = t4.^2;
t15 = sin(t10);
t16 = sin(t11);
FVector = [Iyy.*phidS.*t16.*thtdS-Izz.*phidS.*t16.*thtdS+Ixx.*psidS.*t4.*thtdS-Iyy.*psidS.*t4.*thtdS-Izz.*psidS.*t4.*thtdS-LhS.*LhdS.*m.*phidS.*t14.*2.0-LhS.*g.*m.*t4.*t5-Ixx.*psidS.*t4.*t13.*thtdS.*2.0+Iyy.*psidS.*t4.*t13.*thtdS.*2.0+Ixx.*t3.*t6.*t7.*t12-Iyy.*t3.*t6.*t7.*t12-LhS.*m.*t2.*t4.*yddS+m.*phidS.*t8.*t16.*thtdS+Ixx.*phidS.*psidS.*t3.*t6.*t14.*2.0-Iyy.*phidS.*psidS.*t3.*t6.*t14.*2.0+Ixx.*phidS.*t4.*t7.*t13.*thtdS.*2.0-Iyy.*phidS.*t4.*t7.*t13.*thtdS.*2.0;Iyy.*t9.*t16.*(-1.0./2.0)+(Izz.*t9.*t16)./2.0-Ixx.*psidS.*t15.*thtdS+Iyy.*psidS.*t15.*thtdS+LhS.*m.*t4.*xddS-(m.*t8.*t9.*t16)./2.0-LhS.*LhdS.*m.*thtdS.*2.0+Ixx.*phidS.*psidS.*t4-Iyy.*phidS.*psidS.*t4+Izz.*phidS.*psidS.*t4-LhS.*g.*m.*t2.*t7-Ixx.*phidS.*psidS.*t4.*t13.*2.0+Iyy.*phidS.*psidS.*t4.*t13.*2.0-Ixx.*t4.*t7.*t9.*t13+Iyy.*t4.*t7.*t9.*t13+LhS.*m.*t5.*t7.*yddS;(Ixx.*t12.*t15)./2.0-(Iyy.*t12.*t15)./2.0-Ixx.*phidS.*t4.*thtdS+Iyy.*phidS.*t4.*thtdS-Izz.*phidS.*t4.*thtdS+Ixx.*phidS.*t4.*t13.*thtdS.*2.0-Iyy.*phidS.*t4.*t13.*thtdS.*2.0-Ixx.*t3.*t6.*t9.*t14+Iyy.*t3.*t6.*t9.*t14];
