function MassMatrix = mMtx(Ixx,Iyy,Izz,LhS,m,psiS,thtS)
%MMTX
%    MASSMATRIX = MMTX(IXX,IYY,IZZ,LHS,M,PSIS,THTS)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    22-Apr-2020 17:42:56

t2 = cos(psiS);
t3 = cos(thtS);
t4 = sin(psiS);
t5 = sin(thtS);
t6 = LhS.^2;
t10 = -Iyy;
t7 = t4.^2;
t8 = t5.^2;
t9 = Izz.*t5;
t11 = m.*t6;
t12 = Ixx+t10;
t13 = Ixx.*t7;
t14 = Iyy.*t7;
t15 = t2.*t3.*t4.*t12;
MassMatrix = reshape([Ixx+t11-t13+t14-Ixx.*t8+Izz.*t8-t8.*t11+t8.*t13+t7.*t8.*t10,t15,t9,t15,Iyy+t11+t13+t7.*t10,0.0,t9,0.0,Izz],[3,3]);
